version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: agricounter_db_user
      POSTGRES_PASSWORD: secretDBkeypass
      POSTGRES_DB: agricounter_db
    ports:
      - '8120:5432'
    volumes:
      - agricounter_db:/var/lib/postgresql/data
    networks: 
      - container_net


  myapp:
    build: 
      context: .
    environment:
      DB_SCHEMA: agricounter_db
      DB_USER: agricounter_db_user
      DB_PASSWORD: secretDBkeypass
      DB_HOST: db 
      DB_PORT: 5432 
      NODE_ENV: 'docker'
      AC_IP: myapp
      AC_PORT: "${AC_PORT}"
      AC_PY_PORT: "${AC_PY_PORT}"
      AC_PATH: "${AC_PATH}"
      AC_API_KEY: "${AC_API_KEY}"
      AC_TIMEZONE: "${AC_TIMEZONE}"
    depends_on:
      - db
    ports:
      - '8115:8115'
    volumes:
      - type: bind
        source: /home/myusername/agricounter/backend/src/usr
        target: /opt/app/backend/src/usr
    networks: 
      - container_net

    runtime: nvidia
    restart: always
    
networks:
  container_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/24



volumes:
  agricounter_db:
